#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MarvelApp.XamarinForms.Droid.Resource", IsApplication=true)]

namespace MarvelApp.XamarinForms.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AutoMapper.Android.Resource.String.ApplicationName = global::MarvelApp.XamarinForms.Droid.Resource.String.ApplicationName;
			global::AutoMapper.Android.Resource.String.Hello = global::MarvelApp.XamarinForms.Droid.Resource.String.Hello;
			global::GalaSoft.MvvmLight.Resource.String.ApplicationName = global::MarvelApp.XamarinForms.Droid.Resource.String.ApplicationName;
			global::GalaSoft.MvvmLight.Resource.String.Hello = global::MarvelApp.XamarinForms.Droid.Resource.String.Hello;
			global::Gcm.Client.Resource.String.library_name = global::MarvelApp.XamarinForms.Droid.Resource.String.library_name;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::MarvelApp.XamarinForms.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::MarvelApp.XamarinForms.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int FavoriteIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int HomeIcon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int LoginIcon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int LogoutIcon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int SearchIcon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int SyncIcon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int UnFavoriteIcon = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			// aapt resource value: 0x7f030002
			public const int library_name = 2130903042;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
